// ---------------------------------------------------------------
// See PPT:- "https://docs.google.com/presentation/d/1UnPZV7K6s798RAlkanOFn1iHDK1uMqBJTnzUKYvuT2Q/edit?slide=id.g26fdac204f3_0_892#slide=id.g26fdac204f3_0_892" for more info of this crash course.
// ---------------------------------------------------------------
// Hey everyone in this file we are going to learn for the mutability and immutability in the Rust Programming Language.
// Mutability means the ability to change the value of a variable and immutability means the inability to change the value of a variable. In the Rust Programming Language the variable is immutable by default and if we want to make it mutable then we have to use the mut keyword before the variable name and if we don't use the mut keyword then the variable will be immutable and if we try to change the value of the immutable variable then the compiler will give an error and also if we want to make the variable immutable then we have to use the let keyword before the variable name and if we don't use the let keyword then the variable will be mutable and if we try to change the value of the mutable variable then the compiler will not give any error and also if we want to make the variable mutable then we have to use the mut keyword before the variable name and if we don't use the mut keyword then the variable will be immutable and if we try to change the value of the immutable variable then the compiler will give an error.
// ---------------------------------------------------------------
// In the Rust Programming Language the variable is immutable by default and if we want to make it mutable then we have to use the mut keyword before the variable name and if we don't use the mut keyword then the variable will be immutable and if we try to change the value of the immutable variable then the compiler will give an error and also if we want to make the variable immutable then we have to use the let keyword before the variable name and if we don't use the let keyword then the variable will be mutable and if we try to change the value of the mutable variable then the compiler will not give any error and also if we want to make the variable mutable then we have to use the mut keyword before the variable name and if we don't use the mut keyword then the variable will be immutable and if we try to change the value of the immutable variable then the compiler will give an error.
// ---------------------------------------------------------------
fn main() {
    let mut x:u8 = 255;
    println!("The value stored in the variable x is {}",x);
    x = 200;
    println!("The updated value stored in the variable x is {}",x);
}
// ---------------------------------------------------------------
//As above I have written the code for the mutability and immutability in the Rust Programming Language and also I have explained the concept of the mutability and immutability in the Rust Programming Language and also I have explained the concept of the mut keyword and also I have explained the concept of the let keyword and also I have explained the concept of the variable in the Rust Programming Language and also I have explained the concept of the data types in the Rust Programming Language and also I have explained the concept of the maximum value and minimum value of the data types in the Rust Programming Language and also I have explained the concept of the size of the data types in the Rust Programming Language.
// ---------------------------------------------------------------
// Means first I have enerted the value 255 in the variable num and then I have printed the value stored in the variable num and then I have updated the value stored in the variable num to 200 and then I have printed the updated value stored in the variable num. And also I have explained the concept of the mutability and immutability in the Rust Programming Language and also I have explained the concept of the mut keyword and also I have explained the concept of the let keyword and also I have explained the concept of the variable in the Rust Programming Language and also I have explained the concept of the data types in the Rust Programming Language and also I have explained the concept of the maximum value and minimum value of the data types in the Rust Programming Language and also I have explained the concept of the size of the data types in the Rust Programming Language.
// ---------------------------------------------------------------
// The code ends here. (See docs/README.md for the more information).